name: Setup Swift environment for macOS, Linux and Windows
description: Setup Swift environment by optionally downloading and adding it to the PATH.
author: Soumya Ranjan Mahunt
inputs:
  swift-version:
    description: >-
      Swift version to configure, accepts valid semantic version, "latest", "current".
      Configures latest version for open ended semantic version provided,
      i.e. configures 5.1.1 for 5.1, configures 4.2.4 for 4.
      Provide exact semantic version to configure the same version,
      i.e. configures 5.1 for 5.1.0, configures 5.0 for 5.0.0.
    required: false
    default: 'latest'
  development:
    description: >-
      Whether to include development snapshots matching provided version,
      not required if provided version has no stable release.
    required: false
    default: 'false'
  check-latest:
    description: >-
      Whether to check with latest swift.org versions,
      enabling this option may break this action,
      use cautiously and disable if any issue.
    required: false
    default: 'false'
  dry-run:
    description: >-
      Whether to only get the toolchain data based on version input and skip intallation.
      Can be used with actions that perform custom installations, i.e. using docker tag in Linux.
    required: false
    default: 'false'
  cache-snapshot:
    description: >-
      Whether to cache downloaded toolchain snapshots. Enabled by default,
      can be disabled in case of storage constraints.
    required: false
    default: 'true'
outputs:
  swift-version:
    description: The actual Swift version that was configured.
  toolchain:
    description: JSON formatted toolchain snapshot metadata that was configured.
runs:
  using: node16
  main: dist/index.js
